### ISSUE TITLE
Error in the authentication with twitter

### ISSUE THREAD

**Issue by cdbullones** [flavors/django-graphql-social-auth#17]
### **When the next mutation is made in graphql:**

```
mutation TwitterAuthetication{
  social_auth(provider: "twitter", access_token: "1445260549-Y6i3s6luLmiJC9djgts90IuNCM09mtXfxV0zIAO")
    social
      uid
    }
    token
  }
}

```
**gives me the following error:**

```
{
  "errors": [
    {
      "message": "403 Customer error: Forbidden for url: https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true",
      "Places": [
        {
          "line": 2,
          "Column": 3
        }
      ],
      "way": [
        "social_auth"
      ]
    }
  ],
  "data": {
    "social_auth": null
  }
}
```

**They're following all the conventions, instead with Facebook if it works!**

**Comment by cdbullones** [comment]
**Must be added in access_token
the two keys provided by Twitter in the following format, for authentication to work:**

`oauth_token=1445260549-Zrpj8Hxxxxxxxxxxxxxxxxxxxxxx`

`oauth_token_secret=66w3IvHTOUVxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

```
mutation TwitterAuthetication{
  social_auth(provider: "twitter", access_token: "oauth_token=1445260549-Zrpj8Hxxxxxxxxxxxxxxxxxxxxxx&oauth_token_secret=66w3IvHTOUVxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
    social
      uid
    }
    token
  }
}
```

**Comment by gildniy** [comment]
> **Must be added in access_token the two keys provided by Twitter in the following format, for authentication to work:**
> 
> `oauth_token=1445260549-Zrpj8Hxxxxxxxxxxxxxxxxxxxxxx`
> 
> `oauth_token_secret=66w3IvHTOUVxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
> 
> ```
> mutation TwitterAuthetication{
>   social_auth(provider: "twitter", access_token: "oauth_token=1445260549-Zrpj8Hxxxxxxxxxxxxxxxxxxxxxx&oauth_token_secret=66w3IvHTOUVxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
>     social
>       uid
>     }
>     token
>   }
> }
> ```

This worked for me after hours of struggle.
Why isn't there any documentation talking of this!?
