### ISSUE TITLE
README change proposition

### ISSUE THREAD

**Issue by TitanFighter** [flavors/django-graphql-social-auth#2]
Thank you for this repo and for JWT!!! I have been waiting for something like this for the last 2 months :)

Regarding propositions, I would add the next info to the README:
1. `provider` name can be taken from [this source](https://github.com/python-social-auth/social-core/tree/2fe4060939130e848c4058f0a28509d217b823b5/social_core/backends). Then you need to go to the provider you need and find the variable called `name`. So, this is the exact name which must be provided to `socialAuth(provider:"NAME_VAR_FROM_URL_ABOVE", accessToken:"xxxx")`. For example, for Google OAuth2 it is `google-oauth2` (taken from [here](https://github.com/python-social-auth/social-core/blob/2fe4060939130e848c4058f0a28509d217b823b5/social_core/backends/google.py#L72))

2. For those who are not good with OAuth system, `accessToken` must be provided by the provider (ie Google, Facebook, so on). For example, for Google we can get it in FrontEnd using such code: `gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse().access_token` (of course gapi js client must be uploaded first and user must let you get access to his\her data before you are able to retrieve `access_token`).

3. As I mentioned in Issue #3 :
> From READM it is unclear whether we need to fully replace graphql_social_auth.relay.SocialAuth.Field() by graphql_social_auth.relay.SocialAuthJWT or just the part before .Field().

So I propose to make it a bit clearer.

**Comment by mongkok** [comment]
Hi @TitanFighter and thanks again.
I also think that the documentation could be improved and you have identified the most confusing sections.

Maybe now the doc is clearer.

**Comment by zamaniramin549** [comment]
> 1. name

I'm using as the documentation says but I get
{
  "error": {
    "errors": [
      {
        "message": "Variable \"$provider\" is never used in operation \"SocialAuth\".",
        "locations": [
          {
            "line": 1,
            "column": 21
          }
        ],
        "extensions": {
          "exception": {
            "code": "GraphQLError",
            "stacktrace": [
              "graphql.error.base.GraphQLError: Variable \"$provider\" is never used in operation \"SocialAuth\"."
            ]
          }
        }
      }
    ]
  }
}
