### ISSUE TITLE
Assersition Error

### ISSUE THREAD

**Issue by prabin525** [flavors/django-graphql-social-auth#9]
`UserSocialAuthFilterSet.filter_for_reverse_field` has been removed. `UserSocialAuthFilterSet.filter_for_field` now generates filters for reverse fields. See: https://django-filter.readthedocs.io/en/master/guide/migration.html

I think the error is with django-filters. How to fix this?

**Comment by mongkok** [comment]
Hi @prabin525,
update graphene-django to latest version:

```
pip install graphene-django>=2.2.0 
```

**Comment by mongkok** [comment]
I close the issue, if you have any questions please let me know.
